### ISSUE TITLE
Unable to activate binds longer than g:showmap_autobind_minlen

### ISSUE THREAD

**Issue by metakirby5** [fcpg/vim-showmap#2]
A lot of tpope's [unimpaired](https://github.com/tpope/vim-unimpaired) keybindings have a `co` prefix to toggle something. If I set `let g:showmap_autobind_minlen = 2`, showmap activates on `c`. This is expected, but then pressing `oc` for the `coc` bind only results in "Key(s) not mapped." no matter how quickly I press the keys. Thus, when showmap is open, I have no way of activating any binds longer than `g:showmap_autobind_minlen`.

**Comment by fcpg** [comment]
You should be able to complete a mapping with more than one char left by pressing `<C-x>`, which "resumes" the normal typing. Let me know if this solves your issue.

**Comment by metakirby5** [comment]
`<C-x>` itself seems to give me "Key(s) not mapped" as well. Here are the settings I have:
```vim
let g:showmap_autobind_minlen = 2
let g:showmap_whatis_separator = ' -> '
let g:showmap_auto_whatis_all = 1
let g:showmap_prompt_notrucate = 1
```

**Comment by fcpg** [comment]
Ah, you are in whatis_all -- there might be a bug with <C-x> indeed. Thanks for reporting it, I'll look into it.

**Comment by fcpg** [comment]
Should be fixed; let me know if it works for you, so that I can close the issue!

**Comment by metakirby5** [comment]
Can confirm that `<C-x>` works as intended. Unfortunately, the UX is still a bit less than ideal; I think it would be more pleasant to support multi-key mappings without resuming normal typing, and present them through a "narrowing search". In any case, this issue can be closed.

**Comment by fcpg** [comment]
I agree: I have just added incremental completions, try it out.

**Comment by metakirby5** [comment]
Incremental completions work fantastically! Thank you :)
