### ISSUE TITLE
Unable to activate native keybindings

### ISSUE THREAD

**Issue by metakirby5** [fcpg/vim-showmap#3]
If I have `let g:showmap_autobind_minlen = 2`, I'm unable to activate the `za` toggle fold keybinding at all.

**Comment by fcpg** [comment]
Do you have maps starting with `z` ? I have defined a few exceptions for autobind when maps fall back on key-waiting standard commands eg. `f/F/t/T`. I might have to add `z` in there.

**Comment by metakirby5** [comment]
Yes - `:map z` gives me:

```vim
n  zs          * <Esc>:set foldmethod=syntax<CR>zR
n  zi          * <Esc>:set foldmethod=indent<CR>zR
n  zm          * <Esc>:set foldmethod=marker<CR>zR
```

EDIT: Never mind, [vim-leader-guide](https://github.com/hecal3/vim-leader-guide) has this same issue. I just hadn't even bound `z` to it.

**Comment by fcpg** [comment]
I have added an `g:showmap_no_map_check`, so that in your case you can do:

    let g:showmap_no_map_check = { 'n': { "z": 1 } }

Let me know if this works for you.

**Comment by metakirby5** [comment]
Works great! Thanks.

**Comment by metakirby5** [comment]
Incidentally, is there a reason why this isn't the default behavior for all keybindings?

**Comment by fcpg** [comment]
The idea was to catch typos and prevent the plugin from sending an unexpected sequence of keys that will not trigger a mapping, eg. if the helper is running after typing `co` and the user presses `<Return>`, the plugin will send `co<Return>`, which probably won't do what the user intended.

Having said that, I also see the reasoning behind just sending the keys, so this is now the default (the above `g:showmap_no_map_check ` dictionary is not required anymore). The previous behavior (check the mappings before sending) is available with the new bool option `g:showmap_map_check`.

Thanks for the feedback and suggestions.
