### ISSUE TITLE
Not compatible with nvim (?)

### ISSUE THREAD

**Issue by ghost** [fcpg/vim-showmap#4]
This isn't strictly a bug, unless you intend to be compatible with nvim.  I'm just documenting it for posterity.

First, nvim doesn't support `strcharpart`.  Replacing all `strcharpart` with `strpart` gets past this problem.

nvim also (apparently) does not support `matchstrpos`.  I wasn't able to get past this; is it part of some other plug-in that is shipped with vim?

In any case, there seem to be a number of issues using this plugin with nvim.  FWIW.

--- SER

**Comment by fcpg** [comment]
Thanks for the feedback. I don't know nvim at all, so I can't really comment or adapt the code to it. However, if you know how to programatically test for it, via `has()` or `exists`, and if you know how to tweak the code (`strpart` in the 1st case, probably several calls to replace `matchstrpos`), you can pull request and I will merge.

As a quick note: "
                matchstrpos()
                Same as |matchstr()|, but return the matched string, the start
                position and the end position of the match.  Example:
                        :echo matchstrpos("testing", "ing")
                results in ["ing", 4, 7].
"

**Comment by aeruder** [comment]
This is fixed in newer versions of neovim.  I am using

    NVIM v0.2.0-780-g087acd79

and have both `matchstrpos` and `strcharpart`

I think this can be closed now.

**Comment by fcpg** [comment]
Ok, thanks.
