### ISSUE TITLE
Cant show all map

### ISSUE THREAD

**Issue by yinflying** [fcpg/vim-showmap#7]
Some plugin prefix key map can not show as expected, such as `easymotion`, which has a prefix key binding `<Plug>(easymotion-prefix)`.  Here is the keymap relationship:
```
   ;;            <Plug>(easymotion-prefix)
   <Plug>(easymotion-prefix)N   <Plug>(easymotion-N)
   <Plug>(easymotion-prefix)n   <Plug>(easymotion-n)
   <Plug>(easymotion-prefix)k   <Plug>(easymotion-k)
   <Plug>(easymotion-prefix)j   <Plug>(easymotion-j)
   <Plug>(easymotion-prefix)gE   <Plug>(easymotion-gE)
   <Plug>(easymotion-prefix)ge   <Plug>(easymotion-ge)
   <Plug>(easymotion-prefix)E   <Plug>(easymotion-E)
   <Plug>(easymotion-prefix)e   <Plug>(easymotion-e)
   <Plug>(easymotion-prefix)B   <Plug>(easymotion-B)
   <Plug>(easymotion-prefix)b   <Plug>(easymotion-b)
   <Plug>(easymotion-prefix)W   <Plug>(easymotion-W)
   <Plug>(easymotion-prefix)w   <Plug>(easymotion-w)
   <Plug>(easymotion-prefix)T   <Plug>(easymotion-T)
   <Plug>(easymotion-prefix)t   <Plug>(easymotion-t)
   <Plug>(easymotion-prefix)s   <Plug>(easymotion-s)
   <Plug>(easymotion-prefix)F   <Plug>(easymotion-F)
   <Plug>(easymotion-prefix)f   <Plug>(easymotion-f)
```
when press `;;N` it will map to <Plug>(easymotion-N), However,  vim-showmap  can only resolve the first line. 

Sad, I have read the code , and find that it's hard to solve the problem. :(

**Comment by fcpg** [comment]
Indeed, the plugin won't try and expand maps starting with some mapped prefix.

If really necessary, it should be feasible to re-check for further mappings once a match is found, if the first mapping found allows for remapping, but that would complicate things quite a bit and may slow down general use too.

**Comment by yinflying** [comment]
@fcpg It's a big change, Nearly rewrite the whole plugin.

**Comment by fcpg** [comment]
Right. Closing it for now.
